# Generated by Django 4.1.11 on 2023-09-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirapp', '0002_principalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Requestsir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('mode_of_event', models.CharField(choices=[('Full day', 'Offline'), ('Half day', 'Online')], max_length=255)),
                ('program_type', models.CharField(choices=[('Guest Lecture', 'Guest Lecture'), ('Faculty Development Program', 'Faculty Development Program'), ('Student Development Program', 'Student Development Program')], max_length=255)),
                ('program_topic', models.CharField(max_length=255)),
                ('program_duration', models.CharField(choices=[('Full day', 'Full day'), ('Half day', 'Half day')], max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.CharField(choices=[('B Tech', 'B Tech'), ('B Pharmacy', 'B Pharmacy'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('B Com', 'B Com'), ('BA', 'BA'), ('B Sc', 'B Sc')], max_length=255)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=255)),
                ('branch', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Pharmacy', 'Pharmacy'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Science', 'Science')], max_length=255)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=255)),
                ('name', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('terms_and_conditions', models.BooleanField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirapp.college')),
            ],
        ),
    ]
