# Generated by Django 4.1.11 on 2023-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirapp', '0003_college_requestsir'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255, verbose_name='College Name')),
                ('number_of_days', models.IntegerField(verbose_name='Number of Days')),
                ('date', models.DateField(verbose_name='Date')),
                ('mode_of_event', models.CharField(max_length=255, verbose_name='Mode of Event')),
                ('program_type', models.CharField(max_length=255, verbose_name='Program Type')),
                ('program_topic', models.CharField(max_length=255, verbose_name='Program Topic')),
                ('program_duration', models.CharField(max_length=255, verbose_name='Program Duration')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('course', models.CharField(max_length=255, verbose_name='Course')),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('branch', models.CharField(max_length=255, verbose_name='Branch')),
                ('semester', models.IntegerField(verbose_name='Semester')),
                ('name', models.CharField(max_length=128, verbose_name='Contact Person Name')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile/WhatsApp Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('terms_and_conditions', models.BooleanField(verbose_name='Agree to Terms and Conditions')),
            ],
        ),
    ]
