# Generated by Django 4.1.11 on 2023-09-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirapp', '0005_calevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalrequest',
            name='acknowledgement',
            field=models.BooleanField(default=False, verbose_name='Acknowledgement'),
        ),
    ]
