# Generated by Django 4.1.11 on 2023-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirapp', '0006_finalrequest_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentevent',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
