# Generated by Django 4.1.11 on 2023-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirapp', '0007_studentevent_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherevent',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
